### ISSUE TITLE
Infinite logs produced during build

### ISSUE THREAD

**Issue by alexlarsson** [flathub/com.github.calo001.fondo#3]
So, we just had to shut down a build of this, because it was creating millions of lines of log spew, overloading the flathub build system:  https://flathub.org/builds/#/builders/32/builds/1282

Please don't build it again until we figured out what was causing this.

**Comment by alexlarsson** [comment]
Logs are 3 hours of:
Dee-1.0.gir:12348.1-12348.0: error: unexpected end of file
Dee-1.0.gir:12348.1-12348.0: warning: expected end element of `type'
Dee-1.0.gir:12348.1-12348.0: error: unexpected end of file
Dee-1.0.gir:12348.1-12348.0: warning: expected end element of `type'
....

**Comment by alexlarsson** [comment]
Seens to be looping in these:
```
buildbot 145266  0.0  0.0   5844  2236 pts/3    S+   10:26   0:00 /bin/sh -c echo " VAPIGEN vte-2.91.vapi"; /app/bin/vapigen-0.40 --quiet --library vte-2.91 --metadatadir .   --pkg glib-2.0 --pkg gio-2.0 --pkg pango --pkg gdk-3.0 --pkg gtk+-3.0 ../../bindings/gir/Vte-2.91.gir
buildbot 145268 95.8  0.0  52444 49208 pts/3    S+   10:26   7:23 /app/bin/vapigen-0.40 --quiet --library vte-2.91 --metadatadir . --pkg glib-2.0 --pkg gio-2.0 --pkg pango --pkg gdk-3.0 --pkg gtk+-3.0 ../../bindings/gir/Vte-2.91.gir
```

**Comment by alexlarsson** [comment]
Seems like this is some kind of mismatch between the gir version in gnome 3.32 and the vala in the base app

**Comment by alatiera** [comment]
Bundling `gobject-introspection` seems to mitigate this for now. Version, except micro, should much what was in 3.30

```diff
diff --git a/com.github.calo001.fondo.json b/com.github.calo001.fondo.json
index b074d05..3982f5c 100644
--- a/com.github.calo001.fondo.json
+++ b/com.github.calo001.fondo.json
@@ -38,6 +38,22 @@
         "*.a"
     ],
     "modules" : [
+        {
+            "name": "gobject-introspection",
+            "config-opts": ["--disable-static" ],
+            "ensure-writable": [ "/lib/*/gobject-introspection/giscanner/*.pyc",
+                                 "/lib/*/gobject-introspection/giscanner/*/*.pyc" ],
+            "cleanup-platform": ["/lib/*/gobject-introspection/giscanner",
+                                 "/share/gobject-introspection/giscanner",
+                                 "/bin"],
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://download.gnome.org/sources/gobject-introspection/1.58/gobject-introspection-1.58.0.tar.xz",
+                    "sha256": "27c1590a32749de0a5481ce897772547043e94bccba4bc0a7edb3d8513e401ec"
+                }
+            ]
+        },
         {
             "name" : "libdee",
             "build-options" : {
```

**Comment by alexlarsson** [comment]
> Bundling `gobject-introspection` seems to mitigate this for now. Version, except micro, should much what was in 3.30

Ideally we want to fix this in the base app, because each new app that updates kill flathub. easyssh got it too.

**Comment by alexlarsson** [comment]
Another build of this just started:
https://flathub.org/builds/#/builders/32/builds/1334

Please don't start any more such builds, as each time we need to manually restart the workers to clean things up.
